### PR TITLE
Avoid continually reading needle from fs

### PR DESCRIPTION
**Pull request by zephraph**
I noticed while debugging some slowness around template matching that the needle image is being continually read from the fs. This is especially painful for `waitFor` that essentially loads that image every 500ms. 

I'm not confident that this is the right implementation at the right place and that it shouldn't be augmented w/ the ability to disable it etc. It just seems to me there should be _some_ way to only load the image once if you know it won't change through the execution of your program.

### CODE REVIEW

**Comment by svettwer** [comment]
I like the idea but that a needle changes over time is not impossible. So it would break the contract of how nut.js finds images as the implementation assumes that images behind a certain path are invariant. You already mentioned that as well which is great.

To avoid a contract breaker, I'd agree to add this as an opt-in. So default is "load everything from disk over and over" while it should be configurable to say "the images are invariant, trust me bro!".

For the next major release, one could think about changing the default behavior. I think variable needles are less common than fixed ones, so it would make sense to assume invariant needles but make it possible to load them over and over again, just in case.

**Comment by svettwer** [comment]
I added a proposal to the RFC repo for the next major release. https://github.com/nut-tree/rfc/pull/1

**Comment by zephraph** [comment]
Yep, this more of an example to seed the conversation. It was mostly one of a series of things I was testing to understand why finding items on the screen was so slow. That turned out more to be due to the scaled searches (made configurable in #176) than this.

I'll close this and add my thoughts to the RFC.

**Comment by svettwer** [comment]
Awesome! :+1: 
Thx a lot for your investigation and your thoughts on that! :rocket:

**Pull request closed without merging**
