### PR TITLE
Allows searching for multiple scales to be configurable

### PR DESCRIPTION
**Pull request by zephraph**
In running a small program that was searching for a label in a small, constrained region I was a bit surprised that it could take 5 seconds to find a match. My first thought was io (hence the other pr). Turns out, the multiple scale search is the _vast_ majority of the time. In usecases where the relative size of the needle will be fixed, being able to disable this greatly increases the speed of the search (taking it down to a second or less). 

I haven't added tests yet and I'm sure there's extra doc updating that needs to happen. Wanted to run this by you first to see if it's on track.

### CODE REVIEW

**Comment by s1hofmann** [comment]
Hi @zephraph,

thanks for your contribution!
I really like your implementation, I would've done it the same way hadn't I missed the point that multi-scale search is not exposed via user-facing API 😄.

Like you already mentioned, tests verifying your change would be great 👍 

You already updated the docstring, so API docs are fine.
Additional (user) documentation is not yet in place. One could think about an additional sample in https://github.com/nut-tree/trailmix to highlight multi-scale search, but that shouldn't be a requirement for this PR.

**Review by s1hofmann — CHANGES_REQUESTED** [review]
Tests verifying the change are missing, looks good otherwise 👍

**Comment by s1hofmann** [comment]
@zephraph Any update on this PR?

**Comment by zephraph** [comment]
No updates yet, sorry! Let me follow up tonight.

**Comment by zephraph** [comment]
@s1hofmann let me know if that's enough

**Comment by s1hofmann** [comment]
Hi @zephraph 👋 

Looks good to me, LGTM!

Once again, thanks for your contribution!

**Review by s1hofmann — APPROVED** [review]

**Pull request merged**
